
export const LOAD_IMAGE = 'LOAD_IMAGE'
export const STORE_IMAGE = 'STORE_IMAGE'
export const STORE_IMAGE_LOCAL = 'STORE_IMAGE_LOCAL'
export const IMAGE_ERR = 'IMAGE_ERR'

export const FETCH_NEXT_BATCH = 'FETCH_NEXT_BATCH'

export const STORE_NEXT_BATCH = 'STORE_NEXT_BATCH'

export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE'
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE'

export const STORE_TO_FAVOURITE = 'STORE_TO_FAVOURITE'
export const ADD_TO_FAV = 'ADD_TO_FAV'
